### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.recipe.mkdir#6]
It would be nice to have a new release of this package. The last one is from 2018.

Could you please add me (`icemac`) to PyPI so I can cut a release.

cc: @reinout, @tseaver, @ulif you are the ones who have rights on PyPI.

**Comment by reinout** [comment]
@icemac : done, you should have an invite.

**Comment by icemac** [comment]
@reinout Thank you, I just released https://pypi.org/project/z3c.recipe.mkdir/1.0/.
